Improved version tracking and deprecated SVN
dsavransky/EXOSIMS pull request #403
Opened 2024-11-08 20:08 UTC by VeronicaSergeeva

Replaced SVN-based version tracking in SurveySimulation.py with Git-based tracking using a new utility in version_util.py. This update logs the Python version, package versions, EXOSIMS version, Git commit hash, and tracks uncommitted changes, to ensure compatibility with editable installations and accurate version control.

## Type of change
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- 
## Issue #349

2024-11-22 20:09 UTC, dsavransky requested changes
Global: check all docstrings (make sure all args and returns are documented) and remove all print statements.

2024-11-22 20:09 UTC, dsavransky commented on EXOSIMS/util/version_util.py
> +def is_editable_installation():
This does not appear to be a robust solution across platforms.  We need to figure out a different approach.

2024-11-28 00:17 UTC, VeronicaSergeeva commented
Good evening! I just uploaded two new files (the version_util and SurveySimulation) which addressed the comments we discussed last Friday

2025-03-26 22:03 UTC, dsavransky approved these changes

2025-03-27 15:14 UTC, merged